spring.application.name=examportal
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=examportal;encrypt=true;trustServerCertificate=true
server.port=0
spring.datasource.username=mahima
spring.datasource.password=mahima25
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true